sudo: required
services:
    - docker

before_install:
    - docker build -t khemrajneupane/react-test -f ./frontend/Dockerfile.dev ./frontend
   

script:
    - docker run -e CI=true khemrajneupane/react-test npm test

after_success:
    - docker build -t khemrajneupane/portfolio-frontend ./frontend
    - docker build -t khemrajneupane/portfolio-backend ./portfolio-backend
    - docker build -t khemrajneupane/portfolio-nginx ./nginx

# Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those iamges and push them to docker hub
    - docker push khemrajneupane/portfolio-frontend
    - docker push khemrajneupane/portfolio-backend
    - docker push khemrajneupane/portfolio-nginx
deploy:
    provider: elasticbeanstalk
    region: eu-north-1
    app: khem-portfolio
    env: KhemPortfolio-env
    bucket_name: elasticbeanstalk-eu-north-1-424825972041
    bucket_path: portfolio-khem

    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
