FROM node:alpine

WORKDIR /app

# copy package.json into the container at /api
COPY package*.json /app/

# install dependencies
RUN npm install

# Copy the current directory contents into the container at /api
COPY . /app/

CMD ["npm", "run", "start"]